export type ImpactType =
  | 'DIRECT_DEPENDENCY'
  | 'REVERSE_DEPENDENCY'
  | 'CALLER_IMPACT'
  | 'CALLEE_IMPACT'
  | 'REFERENCE_IMPACT'
  | 'INHERITANCE_IMPACT'
  | 'IMPLEMENTATION_IMPACT'
  | 'FILE_IMPACT'
  | 'DECISION_IMPACT'
  | 'BUG_IMPACT'
  | 'REFACTOR_IMPACT'
  | 'HISTORICAL_COCHANGE'
  | 'ARCHITECTURAL_IMPACT';

export type ImpactEntityType =
  | 'FILE'
  | 'SYMBOL'
  | 'PACKAGE'
  | 'DECISION'
  | 'BUG'
  | 'REFACTOR';
