export type DriftType =
  | 'DEPENDENCY_DIRECTION_DRIFT'
  | 'NEW_CYCLIC_DEPENDENCY'
  | 'COUPLING_INCREASE'
  | 'API_BOUNDARY_DRIFT'
  | 'DIRECTORY_STRUCTURE_DRIFT'
  | 'SYMBOL_RESPONSIBILITY_DRIFT'
  | 'OWNERSHIP_DRIFT'
  | 'ARCHITECTURAL_DECISION_VIOLATION'
  | 'HOTSPOT_ESCALATION'
  | 'RELATIONSHIP_PATTERN_DRIFT';

export type DriftSeverity = 'INFO' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
